name: AutoRun

on:
  #push:
    #branches: 
      #- master
  #watch:
    #types: started
  schedule:
    #格尼尼治时间22：11，东八区北京时间6：11
    - cron: 11 22 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Download git
        run: |
          git clone http://git网址.com
          mv ./UnicomGetCoin/* ./
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: Run program
        run: |
          python3 UnicomAutoGetCoin.py
